name: Maven release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Release with Maven
      run: mvn -B release:prepare --file pom.xml

    - name: Create A Pull Request
      uses: thomaseizinger/create-pull-request@1.3.0
      with:
        # A GitHub API token
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        # The head ref that should be pulled into base.
        head: master
        base: develop
        # The title of the pull request.
        title: Released master into develop
        body: |
              Hi!
              This PR was created in response workflow running.
              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
